### ISSUE TITLE
Question about metrics calculation

### ISSUE THREAD

**Issue by farhadinima75** [liumency/CropLand-CD#3]
Hi @liumency. First of all, your paper and repo are great.

I read your paper and couldn't find out that metrics are calculated over `changed pixels` or the average of `changed and unchanged areas`?

(hint: The BIT and some other methods, calculate metrics over changed pixels only)
BIT:
```
Evaluation Metrics. We use the F1-score with regard to
the change category as the main evaluation indices. F1-score
is calculated by the precision and recall of the test as follows:
```

**Comment by liumency** [comment]
> 
Sorry about the omission.
The metrics are calculated over changed pixels.

**Comment by farhadinima75** [comment]
tnx.
