### ISSUE TITLE
HRSCD数据集下载问题

### ISSUE THREAD

**Issue by DannisZgggg** [liumency/CropLand-CD#4]
尊敬的Dr.Liu，您好：
看到您的论文中引用了HRSCD数据集，想咨询一下HRSCD中2006图像是如何下载的：
[https://ieee-dataport.org/open-access/hrscd-high-resolution-semantic-change-detection-dataset](url)
非常感谢！若方便 是否能共享下，感激不尽！

**Comment by liumency** [comment]
链接：https://pan.baidu.com/s/14D4HxxuYfeMSymXUdSS8ZQ?pwd=1a4d 
提取码：1a4d
