### ISSUE TITLE
HRSCD数据下载异常

### ISSUE THREAD

**Issue by linyiyuan11** [liumency/CropLand-CD#5]
作者您好，我从您贴的链接中下载的HRSCD似乎有异常，您能发一下您处理过的数据集给我吗，不胜感谢。

**Comment by liumency** [comment]
您好，附两个数据集的百度网盘下载连接。建议网络良好时下载。


链接：https://pan.baidu.com/s/1TnjrG2ULj_J7jjzcZjZL7Q?pwd=n7b8&nbsp;
提取码：n7b8&nbsp;
--来自百度网盘超级会员V6的分享

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Oct 25, 2022 10:43 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[liumency/CropLand-CD] HRSCD数据下载异常 (Issue #5)

&nbsp;



 
作者您好，我从您贴的链接中下载的HRSCD似乎有异常，您能发一下您处理过的数据集给我吗，不胜感谢。

**Comment by linyiyuan11** [comment]
非常感谢您的回复，但我从论文中看到您似乎对这个数据集进行了一些处理，请问您还保留有处理后的数据集吗，如果有的话能发一份给我吗，谢谢。

**Comment by linyiyuan11** [comment]
谢谢您

**Comment by yuyuxuyuy** [comment]
> ```
> 非常感谢您的回复，但我从论文中看到您似乎对这个数据集进行了一些处理，请问您还保留有处理后的数据集吗，如果有的话能发一份给我吗，谢谢。
> ``你好，请问你还保留了HRSCD这个数据集吗？我下载的2006年的标签部分有问题，请问你可以分享一下吗？非常感谢！

**Comment by yuyuxuyuy** [comment]
你好，请问你还保留了HRSCD这个数据集吗？我下载的2006年的标签部分有问题，但是上面的连接已经失效了，请问你可以分享一下这个数据集吗？非常感谢！

**Comment by bigshcool** [comment]
> ```
> 非常感谢您的回复，但我从论文中看到您似乎对这个数据集进行了一些处理，请问您还保留有处理后的数据集吗，如果有的话能发一份给我吗，谢谢。
> ```

学姐请问您还保有处理后的代码吗？
